### ISSUE TITLE
bug: 0.1.16 does not count books.google urls at all

### ISSUE THREAD

**Issue by dpriskorn** [internetarchive/iare#42]
https://internetarchive.github.io/iare/?url=https://en.wikipedia.org/wiki/Easter_Island -> 0 google books
but I found many by searching the article e.g.:
![image](https://user-images.githubusercontent.com/68460690/232854251-19291129-b0e9-4166-a8eb-9edf0312bcc8.png)

**Comment by mojomonger** [comment]
Fixed in commit 6043367 

in refFilters.js, the formula i was using was: 

`url.includes("https://archive.org/details/googlebooks")`

which is obviously wrong. i changed it to use:

`url.includes("https://books.google.com/")`

**Comment by dpriskorn** [comment]
Wohoo 🤩
