### ISSUE TITLE
URLs from PDF are inaccurate and do not reflect link in original document

### ISSUE THREAD

**Issue by mojomonger** [internetarchive/iare#48]
From: 

https://www.foundationforfreedomonline.com/wp-content/uploads/2023/03/FFO-FLASH-REPORT-REV.pdf

I see this URL: 

https://www.cisa.gov/topics/election-security/foreign-influence-operations-and-disinformation

But the parser for iare represented that is:

https://www.cisa.gov/topics/election-security/foreign-influence-operations-and-

Resulting in a false 404

**Comment by dpriskorn** [comment]
this is a IARI library issue, see https://github.com/internetarchive/iari/issues/753
