### ISSUE TITLE
2.2: bug: TypeError after publication of new pdf endpoint

### ISSUE THREAD

**Issue by dpriskorn** [internetarchive/iare#54]
we should find another test url that is reachable

https://internetarchive.github.io/iare/?url=https://www.foundationforfreedomonline.com/wp-content/uploads/2023/03/FFO-FLASH-REPORT-REV.pdf&refresh=true
clicking force refresh 1 link pdf
![image](https://github.com/internetarchive/iare/assets/68460690/11bdba54-1329-48a2-b74e-9e8c2efee89d)

**Comment by mojomonger** [comment]
works now.
