### ISSUE TITLE
PDF documents have processing issues

### ISSUE THREAD

**Issue by mojomonger** [internetarchive/iare#62]
Some PDF files cannot be processed by IARE. A new comment should be made here for each one.

**Comment by mojomonger** [comment]
https://www.cambridge.org/core/services/aop-cambridge-core/content/view/3D92A83A6C0BCBEAC55B69F8CBC74CAC/S0892679423000011a.pdf/the-ethics-of-choosing-deterrence.pdf

https://ia601600.us.archive.org/31/items/Book_URLs/DeSantis.pdf

This is a google doc that resolves to a PDF - shall we cover this?
https://drive.google.com/file/d/1lbg0vZ7M7dHdoEQianOVhHqg-YoN7XI5/view?usp=sharing

**Comment by dpriskorn** [comment]
I , prefer an issue for each one with a clear screenshot of the output and the url that was used so I can debug easily

**Comment by dpriskorn** [comment]
Closing this now.
