### ISSUE TITLE
as a developer I want to use the new url= parameter in calls to the article endpoint to avoid a 500 error 

### ISSUE THREAD

**Issue by mojomonger** [internetarchive/iare#7]
In the WikiUrl field, if a wiki article such as: https://en.wikipedia.org/wiki/The_Yardbirds is typed in and "Fetch Data" is pressed, an Error: 500 returns.

The expanded WARI "/statistics/all" url endpoint also gives this error. For instance, putting  this directly in the browser gives an Internal Server Error:

https://archive.org/services/context/wari/v2/statistics/all?lang=en&site=wikipedia&title=The_Yardbirds

but

https://archive.org/services/context/wari/v2/statistics/all?lang=en&site=wikipedia&title=Easter_Island 

does not…might have something to do with caching?

**Comment by dpriskorn** [comment]
This is a bug, but is best circumvented by using the new url= parameter instead which works.

**Comment by dpriskorn** [comment]
done
