### ISSUE TITLE
As a patron: in Reference Viewer, see how the parameter values compare to the required template parameters

### ISSUE THREAD

**Issue by mojomonger** [internetarchive/iare#81]
This will give us a metric for finding out how "close" a reference is to being fully compatible with the the template defined.

**Comment by dpriskorn** [comment]
Could you provide an example showing various degrees of compatibility?

**Comment by mojomonger** [comment]
In Reference Vioewer for an Actionable Item; show in Reference Voewer popup what to do.
BE SPECIFIC!

**Comment by mojomonger** [comment]
closing as no longer applicable
